#ifndef LUAINTERGRATION_GLOBAL_H
#define LUAINTERGRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LUAINTERGRATION_LIBRARY)
#  define LUAINTERGRATION_EXPORT Q_DECL_EXPORT
#else
#  define LUAINTERGRATION_EXPORT Q_DECL_IMPORT
#endif

#endif // LUAINTERGRATION_GLOBAL_H
